### ISSUE TITLE
Self.format in renderer.py?

### ISSUE THREAD

**Issue by ilumsden** [danse-inelastic/journal#4]
In the renderer.py file (/journal/tests/unittests/journal), on line 30, there is the following piece of code:
```
str.append(self.format % line)
```
What is self.format in this case? Is it a string containing some form of string formatting? Or, is the "%" doing something else here?

**Comment by yxqd** [comment]
See https://github.com/danse-inelastic/journal/blob/9e33475f733621e4b01bca08a9a4200bcda45f25/python/journal/devices/Renderer.py#L44

it seems to be "-- %s"
