### ISSUE TITLE
Questions about File.py

### ISSUE THREAD

**Issue by ilumsden** [danse-inelastic/journal#5]
I have two questions about code in the File.py file (/journal/python/journal/components/File.py).

First, on line 40, there is the following code:
```
logfile = file(filename, "a", 0)
```
What are you doing with the `file` constructor? I need to know because it has been removed as of Python 3.0.

Also, on line 44, there is the following syntax:
```
print >> logfile, "...", time.ctime()
```
What does the `>> logfile` syntax do? I've never seen this before, and I can't find anything online about it.

**Comment by yxqd** [comment]
"file" is the file object. It seems replacing "file" with "open" should solve the problem

**Comment by yxqd** [comment]
"print >> logfile" redirects printing out to an output stream, here logfile is the output stream. In python 3, use print(s, file=logfile)

See https://docs.python.org/3/whatsnew/3.0.html#print-is-a-function
