### ISSUE TITLE
Test to Confirm Everything is Working after Adding Python 3 Compatibility?

### ISSUE THREAD

**Issue by ilumsden** [danse-inelastic/journal#7]
Do you have any tests I can run to insure that everything is working now that I've added Python 3 compatibility to all the files in this repository (on the py2to3 branch)?

**Comment by yxqd** [comment]
Tests under https://github.com/danse-inelastic/journal/tree/master/tests/unittests/journal would be good

**Comment by ilumsden** [comment]
Just a note: these tests still need to be performed before merging.

**Comment by yxqd** [comment]
Done
